export const PICK_INGREDIENT:'PICK_INGREDIENT' = 'PICK_INGREDIENT';
export const RESET_INGREDIENT:'RESET_INGREDIENT' = 'RESET_INGREDIENT';
export const SET_INGREDIENTS:'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const ERROR_SET_INGREDIENTS:'ERROR_SET_INGREDIENTS' = 'ERROR_SET_INGREDIENTS';
export const DELETE_INGREDIENT:'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const SET_INFO_INGREDIENT:'SHOW_INFO_INGREDIENT' = 'SHOW_INFO_INGREDIENT';
export const MAKE_ORDER:'MAKE_ORDER' = 'MAKE_ORDER';
export const ERROR_MAKE_ORDER:'ERROR_MAKE_ORDER' = 'ERROR_MAKE_ORDER';
export const INCREMENT_MAP:'INCREMENT_MAP' = 'INCREMENT_MAP';
export const DECREMENT_MAP:'DECREMENT_MAP' = 'DECREMENT_MAP';
export const INCREASE_BUN_MAP:'INCREASE_BUN_MAP' = 'INCREASE_BUN_MAP';
export const DECREASE_BUN_MAP:'DECREASE_BUN_MAP' = 'DECREASE_BUN_MAP';
export const UPDATE_BUN_MAP:'UPDATE_BUN_MAP' = 'UPDATE_BUN_MAP';
export const RESET_MAP:'RESET_MAP' = 'RESET_MAP';
export const SET_BUN:'SET_BUN' = 'SET_BUN';
export const SWITCH_INGREDIENT:'SWITCH_INGREDIENT' = 'SWITCH_INGREDIENT';
export const UPDATE_USER:'UPDATE_USER' = 'UPDATE_USER';
export const UPDATE_VISIT:'UPDATE_VISIT' = 'UPDATE_VISIT';
export const RESET_VISITS:'RESET_VISITS' = 'RESET_VISITS';
export const NETWORK_CONNECTION:'NETWORK_CONNECTION' = 'NETWORK_CONNECTION';







